language: python

notifications:
  email:
    - shihyuay@uci.edu

os:
  - linux

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip uninstall bson && pip install pymongo
  - pip install 'pytest>=3.6'
  - pip install pytest-cov coverage coveralls

script:
  - pytest --disable-pytest-warnings --cov pykg2vec

after_success:
  - coveralls